# Generated by Django 3.0.6 on 2020-07-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Class_insurance', models.CharField(max_length=20)),
                ('Policy_no', models.CharField(max_length=50)),
                ('Claim_no', models.CharField(max_length=20)),
                ('Date_Accident', models.DateTimeField()),
                ('Place', models.CharField(max_length=90)),
                ('Explanation', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Claims',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter Clients Name', max_length=200)),
                ('Class_insured', models.CharField(max_length=255)),
                ('Car_plate', models.CharField(default='KBB 406B', max_length=20)),
                ('Insuerer', models.CharField(max_length=100)),
                ('Policy_no', models.CharField(max_length=255)),
                ('Date_insured', models.DateTimeField()),
                ('Date_expiry', models.DateTimeField()),
                ('Rate', models.CharField(max_length=15)),
                ('Tl', models.CharField(max_length=20)),
                ('Pf', models.CharField(max_length=20)),
                ('Sd', models.CharField(max_length=20)),
                ('Sum_insured', models.CharField(max_length=20)),
                ('Annual_premium', models.IntegerField()),
                ('Commision', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
